apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  namespace: datapower2
  name: dp3
spec:
  license:
    accept: true
    license: L-RJON-BYDR3Q
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: admin-credentials
  domains:
    - certs:
        - certType: usrcerts
          secret: booking-service-alice
        - certType: usrcerts
          secret: booking-service-booking-application
        - secret: sharesecret
          certType: usrcerts
      dpApp:
        config:
          - domain-config
        local:
          - booking-service-file-system
      name: Booking
  version: 10.0-cd
  replicas: 1
